minimumReleaseAge: 0
shamefullyHoist: true
strictPeerDependencies: false

packages:
  - .

allowBuilds:
  '@parcel/watcher': false
  canvas: false
  esbuild: false
  sharp: false
  unrs-resolver: false
  vue-demi: false
  workerd: false

patchedDependencies:
  '@vue-player/vue': patches/@vue-player__vue.patch
